/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface HelloComponent {
        "currentTime": Date;
        "userName": string;
    }
    interface MeteoComponent {
        "appId": string;
    }
    interface SearchComponent {
    }
    interface TimerComponent {
        "currentTime": Date;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSettingsElement extends Components.AppSettings, HTMLStencilElement {
    }
    var HTMLAppSettingsElement: {
        prototype: HTMLAppSettingsElement;
        new (): HTMLAppSettingsElement;
    };
    interface HTMLHelloComponentElement extends Components.HelloComponent, HTMLStencilElement {
    }
    var HTMLHelloComponentElement: {
        prototype: HTMLHelloComponentElement;
        new (): HTMLHelloComponentElement;
    };
    interface HTMLMeteoComponentElement extends Components.MeteoComponent, HTMLStencilElement {
    }
    var HTMLMeteoComponentElement: {
        prototype: HTMLMeteoComponentElement;
        new (): HTMLMeteoComponentElement;
    };
    interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {
    }
    var HTMLSearchComponentElement: {
        prototype: HTMLSearchComponentElement;
        new (): HTMLSearchComponentElement;
    };
    interface HTMLTimerComponentElement extends Components.TimerComponent, HTMLStencilElement {
    }
    var HTMLTimerComponentElement: {
        prototype: HTMLTimerComponentElement;
        new (): HTMLTimerComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-settings": HTMLAppSettingsElement;
        "hello-component": HTMLHelloComponentElement;
        "meteo-component": HTMLMeteoComponentElement;
        "search-component": HTMLSearchComponentElement;
        "timer-component": HTMLTimerComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface HelloComponent {
        "currentTime"?: Date;
        "userName"?: string;
    }
    interface MeteoComponent {
        "appId"?: string;
    }
    interface SearchComponent {
    }
    interface TimerComponent {
        "currentTime"?: Date;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-settings": AppSettings;
        "hello-component": HelloComponent;
        "meteo-component": MeteoComponent;
        "search-component": SearchComponent;
        "timer-component": TimerComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-settings": LocalJSX.AppSettings & JSXBase.HTMLAttributes<HTMLAppSettingsElement>;
            "hello-component": LocalJSX.HelloComponent & JSXBase.HTMLAttributes<HTMLHelloComponentElement>;
            "meteo-component": LocalJSX.MeteoComponent & JSXBase.HTMLAttributes<HTMLMeteoComponentElement>;
            "search-component": LocalJSX.SearchComponent & JSXBase.HTMLAttributes<HTMLSearchComponentElement>;
            "timer-component": LocalJSX.TimerComponent & JSXBase.HTMLAttributes<HTMLTimerComponentElement>;
        }
    }
}
